name: Publish

on:
  release:
    types: [created]

jobs:
  publish-chain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
          registry-url: https://registry.npmjs.org/
          scope: wssz
      - name: Test
        run: |
          npm ci
          npm test
      - name: Build
        run: npm run-script build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}